# Generated by Django 6.0.4 on 2026-04-18 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of_date", models.DateField(unique=True)),
                ("industry_mix", models.JSONField(default=dict)),
                ("geography_mix", models.JSONField(default=dict)),
                ("hhi", models.FloatField(default=0.0)),
                ("total_exposure_inr", models.BigIntegerField(default=0)),
                ("anchor_concentration", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-as_of_date"],
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="e.g. CRP-88421", max_length=32, unique=True
                    ),
                ),
                ("applicant_name", models.CharField(max_length=200)),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("working_capital", "Working Capital"),
                            ("invoice_financing", "Invoice Financing"),
                            ("term_loan", "Term Loan"),
                            ("equipment_loan", "Equipment Loan"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount_inr", models.BigIntegerField()),
                ("sector", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=80)),
                ("vintage_years", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("intake", "Intake"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("debating", "Debating"),
                            ("decided", "Decided"),
                            ("overridden", "Overridden"),
                            ("failed", "Failed"),
                        ],
                        default="intake",
                        max_length=20,
                    ),
                ),
                (
                    "risk_band",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("policy_version", models.CharField(default="v1", max_length=32)),
                ("verdict", models.CharField(blank=True, default="", max_length=32)),
                ("consensus_score", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="cases_case_status_5f99d2_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="cases_case_created_a2f158_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BureauData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cibil_score", models.IntegerField()),
                (
                    "dpd_buckets",
                    models.JSONField(
                        default=dict,
                        help_text="e.g. {'0': 22, '1_30': 2, '31_60': 0, '61_90': 0, '90_plus': 0}",
                    ),
                ),
                ("enquiries_last_6mo", models.IntegerField(default=0)),
                ("active_loans_count", models.IntegerField(default=0)),
                ("utilization_pct", models.FloatField(default=0.0)),
                ("trade_lines", models.JSONField(default=list)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bureau_data",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bureau data",
            },
        ),
        migrations.CreateModel(
            name="BehaviourData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prior_loans_count", models.IntegerField(default=0)),
                ("historical_repayment_pct", models.FloatField(default=0.0)),
                ("avg_tenure_completion_pct", models.FloatField(default=0.0)),
                ("prepayments_count", models.IntegerField(default=0)),
                ("rollover_frequency", models.FloatField(default=0.0)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behaviour_data",
                        to="cases.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_name", models.CharField(max_length=200)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("pan", models.CharField(blank=True, max_length=10)),
                ("industry", models.CharField(max_length=120)),
                ("geography", models.CharField(max_length=120)),
                ("vintage_months", models.IntegerField()),
                ("directors", models.JSONField(blank=True, default=list)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant",
                        to="cases.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_revenue",
                    models.JSONField(
                        default=list, help_text="List of 12-24 monthly revenue figures"
                    ),
                ),
                ("monthly_inflow", models.JSONField(default=list)),
                ("monthly_outflow", models.JSONField(default=list)),
                ("existing_emi", models.IntegerField(default=0)),
                ("bounces_last_6mo", models.IntegerField(default=0)),
                ("avg_monthly_balance", models.IntegerField(default=0)),
                ("dscr", models.FloatField(default=0.0)),
                ("leverage", models.FloatField(default=0.0)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_data",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Financial data",
            },
        ),
        migrations.CreateModel(
            name="IncomeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itr_gross_income", models.BigIntegerField(default=0)),
                ("itr_prior_year", models.BigIntegerField(default=0)),
                ("gst_filings_regular", models.BooleanField(default=True)),
                ("top_3_buyer_concentration_pct", models.FloatField(default=0.0)),
                ("anchor_name", models.CharField(blank=True, max_length=200)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_data",
                        to="cases.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KYCData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kyc_match_pct", models.FloatField(default=99.0)),
                ("pan_gst_linked", models.BooleanField(default=True)),
                ("device_blocklist_hit", models.BooleanField(default=False)),
                ("velocity_anomalies", models.IntegerField(default=0)),
                ("document_authenticity_score", models.FloatField(default=95.0)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_data",
                        to="cases.case",
                    ),
                ),
            ],
        ),
    ]
