# Generated by Django 6.0.4 on 2026-04-18 08:01

import apps.cases.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("cibil", "CIBIL Report"),
                            ("bank_statement", "Bank Statement"),
                            ("gst_certificate", "GST Certificate"),
                            ("gstin_filings", "GSTIN Filings"),
                            ("bank_ac_auth", "Bank Account Authentication"),
                            ("itr", "ITR"),
                            ("ledger", "Ledger"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(upload_to=apps.cases.models._document_upload_path),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                (
                    "source",
                    models.CharField(
                        default="upload", help_text="upload | sample", max_length=32
                    ),
                ),
                ("extracted_meta", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "doc_type"],
                        name="cases_cased_case_id_13ea50_idx",
                    )
                ],
            },
        ),
    ]
