# Generated by Django 6.0.4 on 2026-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_casedocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bureaudata",
            name="cibil_score",
            field=models.IntegerField(default=700),
        ),
    ]
