# Generated by Django 6.0.4 on 2026-04-18 07:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.BigIntegerField(help_text="Per-case monotonic sequence"),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("case.created", "Case created"),
                            ("swarm.started", "Swarm started"),
                            ("agent.started", "Agent started"),
                            ("agent.completed", "Agent completed"),
                            ("agent.failed", "Agent failed"),
                            ("position.recorded", "Position recorded"),
                            ("debate.detected", "Debate detected"),
                            ("lead.intervention", "Lead intervention"),
                            ("decision.final", "Final decision"),
                            ("decision.override", "Decision override"),
                            ("swarm.completed", "Swarm completed"),
                            ("swarm.failed", "Swarm failed"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        help_text="agent:bureau | user:mohit | system", max_length=120
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("prev_hash", models.CharField(default="", max_length=64)),
                ("row_hash", models.CharField(default="", max_length=64)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "ordering": ["case", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["case", "sequence"],
                        name="audit_audit_case_id_12ece7_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="audit_audit_event_t_967cef_idx"
                    ),
                ],
                "unique_together": {("case", "sequence")},
            },
        ),
    ]
