# Generated by Django 6.0.4 on 2026-04-18 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_key",
                    models.CharField(
                        choices=[
                            ("bureau", "Bureau Score Agent"),
                            ("bank", "Bank Statement Agent"),
                            ("fraud", "Fraud Detection Agent"),
                            ("income", "Income Verification Agent"),
                            ("policy", "Policy Agent"),
                            ("behaviour", "Behavioural Agent"),
                            ("lead", "Lead Reviewer"),
                            ("governor", "Final Governor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model", models.CharField(default="", max_length=64)),
                ("prompt_hash", models.CharField(default="", max_length=64)),
                ("seed", models.CharField(default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stance",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("conditional", "Conditional"),
                            ("review", "Review"),
                        ],
                        max_length=16,
                    ),
                ),
                ("confidence", models.FloatField(help_text="0..1")),
                ("score", models.IntegerField(help_text="0..100 for UI display")),
                ("key_metrics", models.JSONField(default=dict)),
                (
                    "flags",
                    models.JSONField(
                        default=list, help_text="list of {severity, code, message}"
                    ),
                ),
                ("rationale", models.TextField()),
                (
                    "dissent_signal",
                    models.JSONField(
                        default=dict, help_text="{disagrees, strength, topic}"
                    ),
                ),
                ("evidence_refs", models.JSONField(default=list)),
                (
                    "agent_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position",
                        to="swarm.agentrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Debate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conflict_pairs",
                    models.JSONField(
                        default=list, help_text="[[agent_a, agent_b, strength, topic]]"
                    ),
                ),
                ("unique_topics", models.JSONField(default=list)),
                ("has_conflict", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debate",
                        to="cases.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("conditional", "Conditional"),
                            ("escalate", "Escalate"),
                        ],
                        max_length=16,
                    ),
                ),
                ("chip_label", models.CharField(default="", max_length=64)),
                ("rationale", models.TextField()),
                ("confidence", models.FloatField(default=0.0)),
                ("constraint_fit", models.CharField(default="", max_length=32)),
                ("audit_strength", models.CharField(default="", max_length=32)),
                ("conditions", models.JSONField(default=list)),
                ("review_checkpoints", models.JSONField(default=list)),
                ("override_by_user", models.CharField(blank=True, max_length=120)),
                ("override_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_decision",
                        to="swarm.agentrun",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_decisions",
                        to="cases.case",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overrides",
                        to="swarm.finaldecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reframed_question", models.TextField()),
                ("proposed_structure", models.TextField()),
                ("conditions", models.JSONField(default=list)),
                ("residual_risks", models.JSONField(default=list)),
                ("escalation_required", models.BooleanField(default=False)),
                (
                    "meters",
                    models.JSONField(
                        default=dict,
                        help_text="uncertainty, conflict, pressure, reversibility 0..100",
                    ),
                ),
                (
                    "agent_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_reconciliation",
                        to="swarm.agentrun",
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_reconciliation",
                        to="cases.case",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["case", "agent_key"], name="swarm_agent_case_id_b0b684_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(fields=["status"], name="swarm_agent_status_b1de71_idx"),
        ),
    ]
